services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: 1
      MSSQL_PID: Developer
    volumes:
      - ./db:/var/opt/mssql/data
    ports:
      - "1433:1433"
    networks:
      - cootranstame_net
    
  cootranstameapi:
    build:
      context: ./AdquisicionesAPI
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - ConnectionStrings__AdquisicionDB=Server=sqlserver;Database=AdquisicionesDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - cootranstame_net
    
  cootranstameweb:
    build:
      context: ./AdquisicionesWEB
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - cootranstameapi
    networks:
      - cootranstame_net

networks:
  cootranstame_net:
    driver: bridge